import { ProviderBaseSDK } from "../../ProviderBaseSDK";
import { IAddEmailRequest, IBlockUnblockRequest, ICardDeliveryCountriesResponse, ICardDetailsRequest, ICardDetailsResponse, ICardHistoryRequest, ICardHistoryResponse, ICardItemResponse, ICardListResponse, ICardNumberResponse, ICardOrderOfferResponse, ICardPayloadCurrenciesResponse, ICardPayloadLimitsRequest, ICardPayloadLimitsResponse, ICardPayloadOfferRequest, ICardPayloadOfferResponse, ICardPayoutRequest, ICardPersonalInfoRequest, ICardPersonalInfoResponse, ICardPoyoutDataResponse, ICardPricesResponse, ICardRequestRequest, ICardRequestResponse, ICommonResponse, IConfirmCardPayloadOfferRequest, IConfirmCardPayloadOfferResponse, IConfirmEmailRequest, IHistoryOperationRequest, IHistoryOperationResponse, IKyc1FinishRequest, IKyc1StartResponse, IKycLimitResponse, IKycStatusResponse, IKycSumSubStartResponse, ILoginRequest, IPhoneConfirmRequest, IPinCodeRequest, IProfileInfoResponse, IProfileRequest, IResendPhoneConfirmRequest, ISignUpRequest, ISignUpResponse, IUpdateAddressCardRequestRequest, IUpdateAddressCardRequestV3Request, IUpdateCardholderNameRequestRequest, IWalletCreateRequest, IWalletResponse, VaultSDKOptions } from "../interfaces/vault.interface";
export declare class VaultProvider extends ProviderBaseSDK {
    private headers;
    private xMerchantId;
    constructor(options: VaultSDKOptions);
    signUp(body: ISignUpRequest): Promise<ICommonResponse>;
    phoneConfirm(body: IPhoneConfirmRequest): Promise<ISignUpResponse>;
    resendPhoneConfirm(body: IResendPhoneConfirmRequest): Promise<ICommonResponse>;
    addEmail(body: IAddEmailRequest, accessToken: string): Promise<ICommonResponse>;
    confirmEmail(body: IConfirmEmailRequest): Promise<ICommonResponse>;
    resendEmailConfirm(accessToken: string): Promise<ICommonResponse>;
    login(body: ILoginRequest): Promise<ISignUpResponse>;
    updateCustomerProfile(body: IProfileRequest, accessToken: string): Promise<void>;
    customerProfileInfo(accessToken: string): Promise<IProfileInfoResponse>;
    createWallets(body: IWalletCreateRequest, accessToken: string): Promise<IWalletResponse>;
    getWallets(accessToken: string): Promise<IWalletResponse>;
    kycStatus(accessToken: string): Promise<IKycStatusResponse>;
    limits(accessToken: string): Promise<IKycLimitResponse>;
    kyc1Start(accessToken: string): Promise<IKyc1StartResponse>;
    kyc1Finish(body: IKyc1FinishRequest, accessToken: string): Promise<IKyc1StartResponse>;
    kycSumSubStart(accessToken: string): Promise<IKycSumSubStartResponse>;
    cardPrices(accessToken: string): Promise<ICardPricesResponse>;
    cardDeliveryCountries(accessToken: string): Promise<ICardDeliveryCountriesResponse>;
    cardList(accessToken: string): Promise<ICardListResponse>;
    cardPoyoutsList(accessToken: string): Promise<ICardPoyoutDataResponse>;
    getPayloadCurrencies(accessToken: string): Promise<ICardPayloadCurrenciesResponse>;
    getPayloadLimits(data: ICardPayloadLimitsRequest): Promise<ICardPayloadLimitsResponse>;
    addCardPayout(data: ICardPayoutRequest): Promise<string>;
    updatePersonalInfo(body: ICardPersonalInfoRequest, accessToken: string): Promise<ICommonResponse>;
    personalInfo(accessToken: string): Promise<ICardPersonalInfoResponse>;
    cardRequest(body: ICardRequestRequest, accessToken: string): Promise<ICardRequestResponse>;
    cancelCardRequest(requestId: number, accessToken: string): Promise<ICommonResponse>;
    updateAddressRequestCard(requestId: number, body: IUpdateAddressCardRequestRequest, accessToken: string): Promise<ICommonResponse>;
    updateAddressRequestCardV3(requestId: number, body: IUpdateAddressCardRequestV3Request, accessToken: string): Promise<ICommonResponse>;
    updateCardholderNameRequestCard(requestId: number, body: IUpdateCardholderNameRequestRequest, accessToken: string): Promise<ICommonResponse>;
    createCardOrderOffer(requestId: number, currency: string, accessToken: string): Promise<ICardOrderOfferResponse>;
    activateCard(cardId: number, code: string, accessToken: string): Promise<ICardItemResponse>;
    payCardOrderOffer(requestId: number, accessToken: string): Promise<ICommonResponse>;
    cardHistory(data: ICardHistoryRequest): Promise<ICardHistoryResponse[]>;
    historyOperations(data: IHistoryOperationRequest): Promise<IHistoryOperationResponse[]>;
    getSoftBlockCodeByCard(cardId: string, accessToken: string): Promise<ICommonResponse>;
    softBlockCard(data: IBlockUnblockRequest): Promise<ICommonResponse>;
    getSoftUnBlockCodeByCard(cardId: string, accessToken: string): Promise<ICommonResponse>;
    softUnBlockCard(data: IBlockUnblockRequest): Promise<ICommonResponse>;
    setPinCode(data: IPinCodeRequest): Promise<ICommonResponse>;
    getCardDetailsCode(cardId: string, accessToken: string): Promise<ICommonResponse>;
    getCardDetails(data: ICardDetailsRequest): Promise<ICardDetailsResponse>;
    getCardNumber(cardId: string, accessToken: string, publicKey: string): Promise<ICardNumberResponse>;
    createCardPayloadOffer(data: ICardPayloadOfferRequest): Promise<ICardPayloadOfferResponse>;
    confirmCardPayloadOffer(data: IConfirmCardPayloadOfferRequest): Promise<IConfirmCardPayloadOfferResponse>;
}
export default VaultProvider;
